In [10]:
#导入数据
import numpy as np
from numpy import *
import pandas as pd

txt_path = '../data/browsing.txt'
f = open(txt_path)
data_lists = f.readlines() 

dataset= []
for data in data_lists:
    data1 = data.strip('\n') 
    data2 = data1.split() 
    dataset.append(data2) 

dataset = np.array(dataset)

#去除重复数据
for i in range(len(dataset)):
    dataset[i] = list(set(dataset[i]))
print(dataset)

[list(['FRO11987', 'ELE89019', 'ELE17451', 'GRO99222', 'SNA90258'])
 list(['SNA30755', 'SNA80192', 'FRO90334', 'ELE26917', 'GRO99222', 'GRO12298', 'ELE52966', 'FRO12685', 'ELE17451', 'ELE91550', 'FRO84225', 'SNA11465'])
 list(['SNA99873', 'DAI22896', 'FRO86643', 'GRO73461', 'ELE17451']) ...
 list(['FRO31317', 'DAI26369', 'SNA44451', 'FRO53271', 'GRO88511', 'GRO88505', 'FRO85605', 'SNA45677', 'FRO41069', 'GRO83463', 'SNA20554', 'SNA62128', 'ELE17451', 'DAI83948', 'DAI18527', 'ELE53126'])
 list(['ELE92920', 'ELE14480', 'ELE74009', 'SNA63881', 'DAI22177', 'DAI92600', 'FRO99756', 'SNA62128', 'ELE56788', 'ELE99751', 'FRO41319', 'DAI62779'])
 list(['SNA63881', 'DAI92600', 'SNA59903', 'DAI45339', 'GRO59710', 'DAI42083', 'DAI62779'])]

<ipython-input-10-cae1d1b043fb>:16: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  dataset = np.array(dataset)

d.

In [24]:
# 1）扫描整个数据集，得到所有出现过的item，作为候选频繁1项集,并记录每个item出现的次数
count1 = {}
for i in dataset:
    for j in i:
        count1[j] = count1.get(j, 0)+1

# 2）筛选出现次数大于100的item,并将出现次数少于100次的item进行剪枝，得到真正的频繁1项集
cut_count1 = {k:v for k, v in count1.items() if v >= 100}
cut_dataset = [[j for j in i if j in cut_count1] for i in dataset]
num_freSeq1=list(cut_count1.keys())
print("frequent items after 1st:",len(num_freSeq1)) 
print('经核验准确')

# 3）生成频繁2项集
count2 = {}
items = cut_count1.keys()
for i in range(len(cut_dataset)):
    for j in range(len(cut_dataset[i])):
        for k in range(j+1, len(cut_dataset[i])):
            pair = tuple(sorted([cut_dataset[i][j],cut_dataset[i][k]]))
            count2[pair] = count2.get(pair,0)+1
cut_count2 = {k:v for k, v in count2.items() if v >= 100} #剪枝生成真正的频繁2项集

# 4) 计算confidence,并列出top5

twoPairs = pd.DataFrame({'pair':cut_count2.keys(), 'count':cut_count2.values()})
twoPairs = twoPairs.sort_values(by = 'count', ascending = False)
twoPairs['countX'] =  twoPairs['pair'].apply(lambda x: cut_count1[x[0]])
twoPairs['countY'] =  twoPairs['pair'].apply(lambda x: cut_count1[x[1]])
twoPairs['confidenceX->Y'] = twoPairs['count']/twoPairs['countX']
twoPairs['confidenceY->X'] = twoPairs['count']/twoPairs['countY']

print('----------------------------------------------------------------------')
print('最终结果为：')
print('\n')
print('support大于100的频繁2项集：')
print(twoPairs['pair'])
print('\n')
print('the top5 confidence:')
print(twoPairs.sort_values(by = 'confidenceX->Y', ascending = False).iloc[:5,:])
print(twoPairs.sort_values(by = 'confidenceY->X', ascending = False).iloc[:5,:])

frequent items after 1st: 647
经核验准确
----------------------------------------------------------------------
最终结果为：


support大于100的频繁2项集：
85      (DAI62779, ELE17451)
239     (FRO40251, SNA80324)
217     (DAI75645, FRO40251)
133     (FRO40251, GRO85051)
135     (DAI62779, GRO73461)
                ...
960     (GRO64900, SNA45677)
1300    (DAI23334, ELE17451)
959     (FRO80039, GRO64900)
909     (ELE86561, SNA45677)
938     (ELE11111, GRO59710)
Name: pair, Length: 1334, dtype: object


the top5 confidence:
                      pair  count  countX  countY  confidenceX->Y  \
634   (DAI93865, FRO40251)    208     208    3881        1.000000
591   (ELE12951, FRO40251)    105     106    3881        0.990566
209   (DAI88079, FRO40251)    446     452    3881        0.986726
955   (DAI43868, SNA82528)    288     296     594        0.972973
1256  (DAI23334, DAI62779)    273     286    6667        0.954545

      confidenceY->X
634         0.053594
591         0.027055
209         0.114919
955         0.484848
1256        0.040948
                     pair  count  countX  countY  confidenceX->Y  \
133  (FRO40251, GRO85051)   1213    3881    1214        0.312548
130  (FRO40251, GRO38636)    106    3881     107        0.027313
218  (FRO40251, FRO92469)    835    3881     849        0.215151
933  (DAI62779, ELE92920)    877    6667    1197        0.131543
997  (DAI62779, SNA18336)    506    6667     709        0.075896

     confidenceY->X
133        0.999176
130        0.990654
218        0.983510
933        0.732665
997        0.713681

In [29]:
twoPairs

,pair,count,countX,countY,confidenceX->Y,confidenceY->X
85,"(DAI62779, ELE17451)",1592,6667,3875,0.238788,0.410839
239,"(FRO40251, SNA80324)",1412,3881,3044,0.363824,0.463863
217,"(DAI75645, FRO40251)",1254,2736,3881,0.458333,0.323113
133,"(FRO40251, GRO85051)",1213,3881,1214,0.312548,0.999176
135,"(DAI62779, GRO73461)",1139,6667,3602,0.170841,0.316213
...,...,...,...,...,...,...
960,"(GRO64900, SNA45677)",100,1046,2455,0.095602,0.040733
1300,"(DAI23334, ELE17451)",100,286,3875,0.349650,0.025806
959,"(FRO80039, GRO64900)",100,2233,1046,0.044783,0.095602
909,"(ELE86561, SNA45677)",100,735,2455,0.136054,0.040733
938,"(ELE11111, GRO59710)",100,811,2004,0.123305,0.049900

e.

In [26]:
count3={}
# 生成频繁3项集
for i in range(len(cut_dataset)):
    temp = cut_dataset[i]
    for j in range(len(temp)):
        for k in range(j+1, len(temp)):
            if tuple(sorted((temp[j],temp[k]))) in cut_count2:
                for m in range(k+1, len(temp)):
                    pair = tuple(sorted((temp[j],temp[k],temp[m])))
                    count3[pair] = count3.get(pair,0) + 1

#筛选出现次数大于100的item,并将出现次数少于100次的item进行剪枝，得到真正的频繁3项集                   
cut_count3 = {k:v for k, v in count3.items() if v >= 100}              

threePairs = pd.DataFrame({'pair':cut_count3.keys(), 'count':cut_count3.values()})
threePairs = threePairs.sort_values(by = 'count', ascending = False)

threePairs['countXY'] = threePairs['pair'].apply(lambda x: cut_count2[tuple(sorted((x[0],x[1])))])
threePairs['countYZ'] = threePairs['pair'].apply(lambda x: cut_count2[tuple(sorted((x[1],x[2])))])
threePairs['countXZ'] = threePairs['pair'].apply(lambda x: cut_count2[tuple(sorted((x[0],x[2])))])

threePairs['confidenceXY->Z'] = threePairs['count']/threePairs['countXY']
threePairs['confidenceYZ->X'] = threePairs['count']/threePairs['countYZ']
threePairs['confidenceXZ->Y'] = threePairs['count']/threePairs['countXZ']




print('----------------------------------------------------------------------')
print('最终结果为：')
print('\n')
print('support大于100的频繁3项集：')
print(threePairs['pair'])
print('\n')
print('the top5 confidence:')
print(threePairs.sort_values(by = 'confidenceXY->Z', ascending = False).iloc[:5,:])
print(threePairs.sort_values(by = 'confidenceYZ->X', ascending = False).iloc[:5,:])
print(threePairs.sort_values(by = 'confidenceXZ->Y', ascending = False).iloc[:5,:])

----------------------------------------------------------------------
最终结果为：


support大于100的频繁3项集：
54     (DAI75645, FRO40251, SNA80324)
44     (DAI62779, FRO40251, SNA80324)
45     (FRO40251, GRO85051, SNA80324)
167    (DAI62779, ELE92920, SNA18336)
77     (DAI62779, DAI75645, SNA80324)
                    ...
228    (DAI75645, GRO46854, GRO73461)
165    (DAI62779, ELE32164, SNA18336)
127    (ELE32164, GRO59710, SNA45677)
39     (DAI62779, FRO40251, GRO38814)
9      (DAI62779, FRO31317, GRO73461)
Name: pair, Length: 233, dtype: object


the top5 confidence:
                               pair  count  countXY  countYZ  countXZ  \
20   (DAI62779, DAI88079, FRO40251)    117      117      446     1070
89   (DAI75645, DAI88079, FRO40251)    148      149      446     1254
21   (DAI88079, ELE17451, FRO40251)    123      124      697      446
232  (DAI42083, DAI62779, DAI92600)    105      117      177      256
217  (FRO19221, SNA53220, SNA93860)    114      155      254      151

     confidenceXY->Z  confidenceYZ->X  confidenceXZ->Y
20          1.000000         0.262332         0.109346
89          0.993289         0.331839         0.118022
21          0.991935         0.176471         0.275785
232         0.897436         0.593220         0.410156
217         0.735484         0.448819         0.754967
                               pair  count  countXY  countYZ  countXZ  \
45   (FRO40251, GRO85051, SNA80324)    471     1213      471     1412
57   (FRO40251, GRO85051, SNA45677)    107     1213      107      309
152  (FRO40251, GRO21487, GRO85051)    120      375      120     1213
65   (FRO40251, FRO53271, GRO85051)    105      309      105     1213
40   (FRO40251, GRO38814, GRO85051)    115      295      115     1213

     confidenceXY->Z  confidenceYZ->X  confidenceXZ->Y
45          0.388293              1.0         0.333569
57          0.088211              1.0         0.346278
152         0.320000              1.0         0.098928
65          0.339806              1.0         0.086562
40          0.389831              1.0         0.094806
                               pair  count  countXY  countYZ  countXZ  \
30   (ELE17451, FRO40251, GRO85051)    217      697     1213      217
137  (DAI31081, FRO40251, GRO85051)    102      280     1213      102
142  (ELE20847, FRO40251, FRO92469)    122      434      835      122
71   (DAI55911, FRO40251, GRO85051)    133      232     1213      133
132  (ELE20847, FRO40251, GRO85051)    139      434     1213      139

     confidenceXY->Z  confidenceYZ->X  confidenceXZ->Y
30          0.311334         0.178895              1.0
137         0.364286         0.084089              1.0
142         0.281106         0.146108              1.0
71          0.573276         0.109646              1.0
132         0.320276         0.114592              1.0

In [28]:
threePairs

,pair,count,countXY,countYZ,countXZ,confidenceXY->Z,confidenceYZ->X,confidenceXZ->Y
54,"(DAI75645, FRO40251, SNA80324)",550,1254,1412,1130,0.438596,0.389518,0.486726
44,"(DAI62779, FRO40251, SNA80324)",476,1070,1412,923,0.444860,0.337110,0.515710
45,"(FRO40251, GRO85051, SNA80324)",471,1213,471,1412,0.388293,1.000000,0.333569
167,"(DAI62779, ELE92920, SNA18336)",432,877,455,506,0.492588,0.949451,0.853755
77,"(DAI62779, DAI75645, SNA80324)",421,882,1130,923,0.477324,0.372566,0.456121
...,...,...,...,...,...,...,...,...
228,"(DAI75645, GRO46854, GRO73461)",101,190,389,712,0.531579,0.259640,0.141854
165,"(DAI62779, ELE32164, SNA18336)",100,832,124,506,0.120192,0.806452,0.197628
127,"(ELE32164, GRO59710, SNA45677)",100,911,189,224,0.109769,0.529101,0.446429
39,"(DAI62779, FRO40251, GRO38814)",100,1070,295,389,0.093458,0.338983,0.257069
9,"(DAI62779, FRO31317, GRO73461)",100,376,395,1139,0.265957,0.253165,0.087796